"""Constants"""

HOME_MSG = (f"\nUP Arrow: Increase Speed\nDown Arrow : Decrease Speed\n"
                f"E/e: End Ride\nP/p: Pause Ride\nR/r: Resume Ride\n")
START_RIDE_MSG = "Ride is started and current speed is zero"
DRIVING = "driving"
WAITING =  "waiting"
WAITING_STATE = "Your ride is in waiting state..."
SPEED_UNIT = "Meter per Second"
FARE_UNIT = "$"
RIDE_TIME = "Ride Time:"
DISTANCE = "Distance:"
SPEED = "Speed:"
FARE = "Fare:"
WAIT_TIME= "Wait Time:"
CURSOR_UP_ONE = "\x1b[1A" 
ERASE_LINE = "\x1b[2K"
